### PR TITLE
solve private header dependency for X11 global shortcuts

### PR DESCRIPTION
**Pull request by antis81**
@pvanek Can you please review CMakeLists.txt and check on OSX? This change actually should be part of the unmaintained libQxt library.

### CODE REVIEW

**Comment by antis81** [comment]
Fixes #168

**Comment by antis81** [comment]
@pvanek **poke** please reply, so we can solve this. I'm not going to contribute to the unmaintained `libqxt`. Like I tried to say in other post, we need to get rid of those dependencies. Why? First, libQxt is unmaintained :arrow_right: becomes unstable over time. We should rather make this a part to Qt itself!

**Comment by jleclanche** [comment]
It looks fine, I'm landing this.

**Comment by antis81** [comment]
@jleclanche Thanks! Will reduce headaches to lot of developer's. :+1:

**Pull request merged**
