### PR TITLE
Add chinese translation

### PR DESCRIPTION
**Pull request by losywee**
Add a Simplified Chinese translation for qterminal.

### CODE REVIEW

**Comment by jleclanche** [comment]
I don't think that's how access keys are supposed to be done in cjk..

**Comment by losywee** [comment]
Maybe you are correct, but it is not cjk to do. I am sorry that I can't understand you issue. I only want to translate it to Simplified Chinese translation.

**Comment by pvanek** [comment]
maybe it makes sense. Alt+<char> is listed in ascii sequence as part of simplified chinese strings. Maybe it's standard in zh_CN, who knows ;)

**Comment by u-ho-bros** [comment]
Simplified Chinese translation is not working .
Startup translation files [qterminal_zh_CN.qm] for is not loaded .
To fix the problem , you must modify the main.cpp.

--------------------------------------------------------------------------
[kuma@kuma-manjaro-vm ~]$ export LANG='zh_CH.UTF-8'
[kuma@kuma-manjaro-vm ~]$ qterminal 

(process:1418): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
iconTheme "Compass"
TRANSLATIONS_DIR: Loading translation file "qterminal_zh.qm" from dir /usr/share/qterminal/translations
load success: false

**Comment by losywee** [comment]
Thanks for your reply. Yes, I had known currently, maybe I am a string idiot, oha...

**Comment by u-ho-bros** [comment]
Please look at the pull request # 175.
I like that can be displayed in Chinese, it attempted to fix.
I In the environment have menu can be displayed in Chinese.
manjaro_lxqt

**Comment by losywee** [comment]
Yes, Thanks.

**Comment by losywee** [comment]
To be honest, I translate it by Japanese translation. I am sorry for the careless pedestrian.

**Pull request merged**
