### PR TITLE
Drop Qt4 compatibility 

### PR DESCRIPTION
**Pull request by jleclanche**
This commit drops qt versions <5.2.

### CODE REVIEW

**Comment by jleclanche** [comment]
@pvanek without comments I will be merging this. There's no strong incentive to support qt<5 here.

**Comment by pvanek** [comment]
please wait with it a bit. There are still some usage for qt4. But thanks anyway - I'll handle it later "when debian drops qt4" (which seems near)

**Comment by agaida** [comment]
please merge it now - qterminal will go to sid with qt5 - and eventually backported to stable also with qt5

**Comment by jleclanche** [comment]
@pvanek Qt4 is completely phased out. I think it's time.

**Comment by jleclanche** [comment]
Rebased and ready to land.

**Pull request merged**
