### PR TITLE
Changed layout of font-setting to better fit to the other settings in th...

### PR DESCRIPTION
**Pull request by worblehat**
...e widget.

**Before**:

settings_before

**After**:

settings_after

### CODE REVIEW

**Comment by jleclanche** [comment]
Can you swap the position of the change button and the display?

**Comment by worblehat** [comment]
Done. That's indeed better.

settings_after_2

**Comment by jleclanche** [comment]
Thanks, gtm

**Comment by jleclanche** [comment]
Come to think of it, why not use a QFontComboBox?

**Comment by pvanek** [comment]
my 2c: I'd say - keep using group box. It really helps with logic widget organization in this case.

QFontComboBox was used originally and it's really slow on initialisation. The prefs dialog appeared after some seconds - not immediately - using QFontComboBox.

**Comment by jleclanche** [comment]
OK then

**Pull request merged**
